<div class="wrap">
    <h2>Reports</h2>

    <div id="dashboard-widgets-wrap">

        <div id="dashboard-widgets" class="metabox-holder">

            <div class="postbox-container">
                <div class="meta-box-sortables">
                    <div class="postbox">
                        <h3 class="hndle"><span>Profit and Loss</span></h3>
                        <div class="inside">
                            <p>Shows money you earned (income) and money you spent (expenses) so you can see how profitable you are. Also called an income statement.</p>

                            <p><a class="button button-primary" href="#">View Report</a></p>
                        </div>
                    </div><!-- .postbox -->

                    <div class="postbox">
                        <h3 class="hndle"><span>Company Snapshot</span></h3>
                        <div class="inside">
                            <p>Displays your income and expenses in year-over-year comparisons using pie charts and bar graphs.</p>

                            <p><a class="button button-primary" href="#">View Report</a></p>
                        </div>
                    </div><!-- .postbox -->

                    <div class="postbox">
                        <h3 class="hndle"><span>Expenses by Vendor Summary</span></h3>
                        <div class="inside">
                            <p>This report shows your total expenses for each vendor.</p>

                            <p><a class="button button-primary" href="#">View Report</a></p>
                        </div>
                    </div><!-- .postbox -->

                    <div class="postbox">
                        <h3 class="hndle"><span>Statement of Cash Flows</span></h3>
                        <div class="inside">
                            <p>Shows cash generated by your business (operating activities), cash spent on your business (investments) and cash in or out from stock and dividends (financing).</p>

                            <p><a class="button button-primary" href="#">View Report</a></p>
                        </div>
                    </div><!-- .postbox -->
                </div><!-- .meta-box-sortables -->
            </div><!-- .postbox-container -->

            <div class="postbox-container">
                <div class="meta-box-sortables">
                    <div class="postbox">
                        <h3 class="hndle"><span>Balance Sheet</span></h3>
                        <div class="inside">
                            <p>Lists what you own (assets), what your debts are (liabilities), and what you’ve invested in your company (equity).</p>

                            <p><a class="button button-primary" href="#">View Report</a></p>
                        </div>
                    </div><!-- .postbox -->

                    <div class="postbox">
                        <h3 class="hndle"><span>A/R Aging Summary</span></h3>
                        <div class="inside">
                            <p>Shows unpaid invoices for the current period and for the last 30, 60 and 90+ days so you can see how long they’ve been open (outstanding).</p>

                            <p><a class="button button-primary" href="#">View Report</a></p>
                        </div>
                    </div><!-- .postbox -->

                    <div class="postbox">
                        <h3 class="hndle"><span>A/P Aging Summary</span></h3>
                        <div class="inside">
                            <p>Shows unpaid bills for the current period and for the last 30, 60 and 90+ days so you can see how long they’ve been open (outstanding).</p>

                            <p><a class="button button-primary" href="#">View Report</a></p>
                        </div>
                    </div><!-- .postbox -->

                    <div class="postbox">
                        <h3 class="hndle"><span>Vendor Balance Summary</span></h3>
                        <div class="inside">
                            <p>Shows the total amount you owe each vendor.</p>

                            <p><a class="button button-primary" href="#">View Report</a></p>
                        </div>
                    </div><!-- .postbox -->
                </div><!-- .meta-box-sortables -->
            </div><!-- .postbox-container -->
        </div><!-- .metabox-holder -->
    </div><!-- .dashboar-widget-wrap -->

</div>